name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore packages
        run: dotnet paket restore

      - name: Build code
        run: dotnet build -c Release FCQRS.sln

      - name: Generate documentation
        run: dotnet fsdocs build --properties Configuration=Release

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
